[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "TKTotalConversion"
description = "Bring Battle Royale to your viewers with Team Kill: Total Conversion!"
websiteUrl = "https://github.com/wwwDayDream/TKTotalConversion"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
www_Day_Dream-SFXMixerPatch = "0.1.1"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "../dist"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/TKTotalConversion.dll"
target = "/BepInEx/plugins/TKTotalConversion/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "mods" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
